#!/usr/bin/env python3

import psycopg2
import sys

def mostarticles():

    # Queries are executed from the tables and views in the news database
    cursor.execute(
        "SELECT * from mostview")

    # Result is a python list
    results = cursor.fetchall()

    # Text is generated as output from the print statement of total views of
    # of top three most read articles
    print ("What are the most popular three articles of all time?")
    i = 0
    while i < 3:
        title = results[i][1]
        views = results[i][2]
        print(title + "- %d" % (views) + " views")
        i = i + 1


def main():
    """Text generated of top three most read articles by connecting to 
    the news database and queries executed"""

    # Makes connection to the news database
    conn = psycopg2.connect(database="news", user="vagrant",
                            password="vagrant", host="localhost")
    cursor = conn.cursor()

    mostarticles()    

    # The connection to the news database is closed.
    conn.close()


if __name__ == "__main__":
    main()